### PR TITLE
Add `Capital_Underscore_Form`

### PR DESCRIPTION
**Pull request by awr1**
I use this form a few times in my code - not quite `UPCASE_FORM` but instead where the first character of each word is capitalized. The `string-inflection-capital-underscore-p` function I did could probably be better, but regex is not my forte...

### CODE REVIEW

**Comment by akicho8** [comment]
Thank you PR.
By the way Capital underscore is a format used in what languages?

**Comment by awr1** [comment]
I've used it from time to time. [OCaml guidelines (ironically, given OCaml's name) do something sort of like this, but it's only the first word that is capitalized.](https://github.com/ocaml/ocaml/blob/trunk/otherlibs/raw_spacetime_lib/raw_spacetime_lib.ml) 

Someone else called it "Cobra Case" [here](https://www.alfredforum.com/topic/4818-code-case/).

**Comment by akicho8** [comment]
Thank you.
I have looked at the reference URL.
On that basis, I have a little doubt.

1. `Foo_Bar` is not `capital underscore`. Is not it `cobra case` ?
   Searching for `capital underscore` will find https://github.com/s-hiroshi/development-guide-public/blob/master/coding-guide/README.md
   `FOO_BAR` format is called `capital underscore`. It is likely to get confused.

2. Are you programmers using OCaml?
If so, there is no use for the `Foo_Bar` format. Do you need the `Foo_bar` format?

3. What is the name of Ocaml's `Foo_bar` format?

**Comment by awr1** [comment]
I have programmed in OCaml occasionally but I don't know what they call that sort of format. Maybe it should be called "Objective_case?"

I remember seeing some C++ code that used this "Cap_Underscore" style a few years ago for types but I don't remember where it was. If you don't think it's popular enough to warrant an addition (as I myself had difficulty looking this type of style up online) to this package feel free to close this.

**Comment by akicho8** [comment]
understood. You want to use it on a personal project.
Let's add capital underscore style if you need it.
Since string-inflection itself was originally for yourself, I would like to add a conversion rule if there is demand for even one person.

**Comment by akicho8** [comment]
We fixed it because there was a part which did not fit a little with master's latest.
So please try using master's latest.

**Pull request merged**
